version: "3.8"

services:
  qdrant:
      image: qdrant/qdrant:latest
      restart: always
      container_name: qdrant
      ports:
        - 6333:6333
        - 6334:6334
      expose:
        - 6333
        - 6334
        - 6335
      volumes:
        - ./qdrant_data:/qdrant_data
      # environment:
      #   - QDRANT__LOG_LEVEL=TRACE

  embeddings:
      image: mimir-embeddings:latest
      restart: always 
      container_name: embeddings
      ports:
        - 3000:3000
      expose:
        - 3000